### ISSUE TITLE
GNU stow for symlinks

### ISSUE THREAD

**Issue by 1Kill2Steal** [CelestialCrafter/dotfiles#1]
# Better repository organization via GNU stow

This is a feature suggestion for the sake of managing your configuration directories outside of `~/.config`. There are some files like `.bashrc`/`.zshrc` and `.gitconfig` that stay inside `~/` rather than `~/.config` and you can make use of [GNU stow](https://www.gnu.org/software/stow/) to create symbolic links for your other configuration folders.

## Setup

You can set up a shell script to initialize all of the symlinks like so:

Assume we have this directory structure

```md
  ~/dotfiles
  │ <!-- Other configurations for different directories -->
  │ home/       
  │ │ dot-gitconfig                  
  │ │ dot-tmux.conf                  
  │ └ dot-zshrc          
  └ stow_setup.sh            
```

You can write the `~/dotfiles/stow_setup.sh` script like so:

```sh
#!/bin/sh

if ! command -v stow >/dev/null 2>&1; then
	echo "You need to have GNU stow installed."
	exit 1
fi

cd ~/dotfiles

stow --dotfiles home/ -t "$HOME/"
# Other stow symlinks
```

### Running it

```sh
chmod +x ~/dotfiles/stow_setup.sh
./stow_setup.sh
```

### Result

```sh
$ cd
$ ls -al
# Other files
lrwxrwxrwx    1 $USER $USER        28 May 21 00:30 .zshrc -> dotfiles/home/dot-zshrc
lrwxrwxrwx    1 $USER $USER        32 May 21 00:30 .gitconfig -> dotfiles/home/dot-gitconfig
lrwxrwxrwx    1 $USER $USER        32 May 21 00:30 .tmux.conf -> dotfiles/home/dot-tmux.conf
# Other files
```

Those arrows (`->`) mean that the files are symlinks now. Any change done on `~/.zshrc` reflects upon `~/dotfiles/home/dot-zshrc` and vice versa.

## Additional notes

The `--dotfiles` flag is used to substitute all the files in the folder that start with `dot-` as a normal `.`. The reason for that is so the files in the `dotfiles/` repository don't become hidden. The `-t` flag is for the target directory. There are also some other nice flags which you can refer to at the manual. Here's the [manpage](https://man.archlinux.org/man/stow.8) on `archlinux.org`.

---

Here are some YouTube vids that cover the same topic of using GNU stow:

- [Dreams of Autonomy](https://youtu.be/y6XCebnB9gs)

- [Fireship](https://youtu.be/r_MpUP6aKiQ)

**Comment by CelestialCrafter** [comment]
sounds good!! i can either implement it when i have time, or if you make a pull request ill merge it

**Comment by 1Kill2Steal** [comment]
> sounds good!! i can either implement it when i have time, or if you make a pull request ill merge it

I'll check the repository out more tomorrow to see how it's structured and make use of stow for it. Are all of your files on the repo currently just `.config` directory files?
