### ISSUE TITLE
waybar css

### ISSUE THREAD

**Issue by doctordrogon** [CelestialCrafter/dotfiles#3]
hi, where's the way bar css? among the issues i'm having trying to replicate your setup, i can't seem to find the waybar css anywhere.

**Comment by CelestialCrafter** [comment]
dot-config/waybar/style.css

**Comment by doctordrogon** [comment]
i say this because it pretty much imports itself in the style.css file.

**Comment by CelestialCrafter** [comment]
wdym? if your talking about the `@import` at the top, that's [auto-generated by pywal](https://github.com/dylanaraps/pywal/blob/master/pywal/templates/colors-waybar.css).

**Comment by doctordrogon** [comment]
interesting. also, can i add you on discord or something? configuring this is difficult. also i'm not sure i should be asking for that, i rarely use github lol

**Comment by CelestialCrafter** [comment]
mhm! I'm celestialexe on discord
